name = "Botanical"
license = "MIT"
licenselink = "https://github.com/m-okeefe/hugo-botanical/blob/master/LICENSE"
description = "a portfolio theme"
tags = ["poetry", "writing", "portfolio", "static", "clean", "minimal", "green"]
min_version = "0.41"

[author]
  name = "Megan O'Keefe"